# Generated by Django 2.0.4 on 2018-11-15 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nextseq_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenomeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genome_name', models.CharField(max_length=50)),
                ('species', models.CharField(choices=[('human', 'Human'), ('mouse', 'Mouse'), ('rat', 'rat'), ('other (please explain in notes)', 'other (please explain in notes)')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_id', models.CharField(max_length=100, verbose_name='library name')),
                ('experiment_index', models.CharField(blank=True, max_length=20)),
                ('experiment_type', models.CharField(choices=[('ATAC-seq', 'ATAC-seq'), ('ChIP-seq', 'ChIP-seq'), ('Hi-C', 'Hi-C'), ('scATAC-seq', 'scATAC-seq'), ('scRNA-seq', 'scRNA-seq'), ('snRNA-seq', 'snRNA-seq'), ('4C', '4C'), ('CUT&RUN', 'CUT&RUN'), ('other (please explain in notes)', 'other (please explain in notes)')], max_length=50, null=True)),
                ('reference_to_notebook_and_page_number', models.CharField(max_length=50, null=True)),
                ('date_started', models.DateField(blank=True, help_text='If the datepicker is not working, please enter in this form: yyyy-mm-dd, like 2018-04-03', null=True)),
                ('date_completed', models.DateField(blank=True, help_text='If the datepicker is not working, please enter in this form: yyyy-mm-dd, like 2018-04-03', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProtocalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocal_name', models.CharField(max_length=50)),
                ('experiment_type', models.CharField(choices=[('ATAC-seq', 'ATAC-seq'), ('ChIP-seq', 'ChIP-seq'), ('Hi-C', 'Hi-C'), ('scATAC-seq', 'scATAC-seq'), ('scRNA-seq', 'scRNA-seq'), ('snRNA-seq', 'snRNA-seq'), ('4C', '4C'), ('CUT&RUN', 'CUT&RUN'), ('other (please explain in notes)', 'other (please explain in notes)')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SampleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, verbose_name='sample name')),
                ('date', models.DateField(blank=True, help_text='If the datepicker is not working, please enter in this form: yyyy-mm-dd, like 2018-04-03', null=True)),
                ('sample_index', models.CharField(blank=True, max_length=20)),
                ('species', models.CharField(choices=[('human', 'Human'), ('mouse', 'Mouse'), ('rat', 'rat'), ('other (please explain in notes)', 'other (please explain in notes)')], max_length=10)),
                ('sample_type', models.CharField(choices=[('cultured cells', 'cultured cells'), ('isolated cells', 'isolated cells'), ('isolated nuclei', 'isolated nuclei'), ('tissue', 'tissue'), ('other (please explain in notes)', 'other (please explain in notes)')], max_length=50)),
                ('preparation', models.CharField(choices=[('flash frozen without cryopreservant', 'flash frozen without cryopreservant'), ('flash frozen with cryopreservant', 'flash frozen with cryopreservant'), ('slow frozen with cryopreservant', 'slow frozen with cryopreservant'), ('fresh', 'fresh'), ('other (please explain in notes)', 'other (please explain in notes)')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('team_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeqBioInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_version', models.CharField(blank=True, max_length=200)),
                ('final_reads', models.IntegerField(blank=True, null=True)),
                ('final_yield', models.FloatField(blank=True, null=True)),
                ('mito_frac', models.FloatField(blank=True, null=True)),
                ('tss_enrichment', models.FloatField(blank=True, null=True)),
                ('frop', models.FloatField(blank=True, null=True)),
                ('genome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterseq_app.GenomeInfo')),
            ],
        ),
        migrations.CreateModel(
            name='SeqInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_id', models.CharField(max_length=100, unique=True)),
                ('read_length', models.CharField(blank=True, max_length=50)),
                ('read_type', models.CharField(choices=[('SE', 'Single-end'), ('PE', 'Paired-end'), ('other (please explain in notes)', 'other (please explain in notes)')], max_length=50, null=True)),
                ('portion_of_lane', models.FloatField(blank=True, null=True)),
                ('total_reads', models.IntegerField(blank=True, null=True)),
                ('date_submitted_for_sequencing', models.DateField(blank=True, help_text='If the datepicker is not working, please enter in this form: yyyy-mm-dd, like 2018-04-03', null=True)),
                ('default_label', models.CharField(blank=True, max_length=200, verbose_name='Default Label(for setQC report)')),
                ('notes', models.TextField(blank=True)),
                ('i5index', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequencing_i5_index', to='nextseq_app.Barcode')),
                ('i7index', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequencing_i7_index', to='nextseq_app.Barcode')),
                ('libraryinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterseq_app.LibraryInfo')),
            ],
        ),
        migrations.CreateModel(
            name='SeqMachineInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=50)),
                ('sequencing_core', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='seqinfo',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterseq_app.SeqMachineInfo'),
        ),
        migrations.AddField(
            model_name='seqinfo',
            name='team_member_initails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seqbioinfo',
            name='seqinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterseq_app.SeqInfo'),
        ),
        migrations.AddField(
            model_name='libraryinfo',
            name='protocalinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterseq_app.ProtocalInfo'),
        ),
        migrations.AddField(
            model_name='libraryinfo',
            name='sampleinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterseq_app.SampleInfo'),
        ),
        migrations.AddField(
            model_name='libraryinfo',
            name='team_member_initails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
