# Generated by Django 2.0.6 on 2018-10-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterseq_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenomeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genome_name', models.CharField(max_length=50)),
                ('species', models.CharField(choices=[('Human', 'Human'), ('Mouse', 'Mouse'), ('Other', 'Other')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProtocalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocal_name', models.CharField(max_length=50)),
                ('experiment_type', models.CharField(choices=[('ATAC-seq', 'ATAC-seq'), ('ChIP-seq', 'ChIP-seq'), ('HiC', 'HiC'), ('Other', 'Other')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SequencingMachineInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=50)),
                ('sequencing_core', models.CharField(max_length=50)),
            ],
        ),
    ]
