# Generated by Django 2.0.6 on 2018-10-15 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterseq_app', '0002_genomeinfo_protocalinfo_sequencingmachineinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, unique=True)),
                ('sample_index', models.CharField(blank=True, max_length=20)),
                ('species', models.CharField(choices=[('Human', 'Human'), ('Mouse', 'Mouse'), ('Other', 'Other')], max_length=10)),
                ('sample_type', models.CharField(choices=[('cultured cell', 'cultured cell'), ('isolated nuclei', 'isolated nuclei'), ('tissue', 'tissue'), ('PcA cell line', 'PcA cell line'), ('other', 'other')], max_length=50)),
                ('preparation', models.CharField(choices=[('slow frozen with cryopreservant', 'slow frozen with cryopreservant'), ('flash frozen', 'flash frozen'), ('douncing homogenization', 'douncing homogenization'), ('other', 'other')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='SamplesInfo',
        ),
        migrations.AddField(
            model_name='libraryinfo',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libraryinfo',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libraryinfo',
            name='experiment_index',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='libraryinfo',
            name='experiment_type',
            field=models.CharField(choices=[('ATAC-seq', 'ATAC-seq'), ('ChIP-seq', 'ChIP-seq'), ('HiC', 'HiC'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='libraryinfo',
            name='notes',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='libraryinfo',
            name='protocalinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterseq_app.ProtocalInfo'),
        ),
        migrations.AddField(
            model_name='libraryinfo',
            name='reference_to_notebook_and_page_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='libraryinfo',
            name='team_member_initails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='libraryinfo',
            name='sampleinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterseq_app.SampleInfo'),
        ),
    ]
