# Generated by Django 2.0.6 on 2018-10-15 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nextseq_app', '0012_auto_20180926_1126'),
        ('masterseq_app', '0003_auto_20181015_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencinginfo',
            name='i5index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequencing_i5_index', to='nextseq_app.Barcode'),
        ),
        migrations.AddField(
            model_name='sequencinginfo',
            name='i7index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequencing_i7_index', to='nextseq_app.Barcode'),
        ),
        migrations.AddField(
            model_name='sequencinginfo',
            name='libraryinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterseq_app.LibraryInfo'),
        ),
        migrations.AddField(
            model_name='sequencinginfo',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterseq_app.SequencingMachineInfo'),
        ),
        migrations.AddField(
            model_name='sequencinginfo',
            name='portion_of_lane',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sequencinginfo',
            name='read_type',
            field=models.CharField(choices=[('SE', 'Single-end'), ('PE', 'Paired-end')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='sequencinginfo',
            name='sequencing_length',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sequencinginfo',
            name='team_member_initails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
