# Generated by Django 2.0.6 on 2018-10-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterseq_app', '0004_auto_20181015_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencinginfo',
            name='portion_of_lane',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
