# Generated by Django 2.0.6 on 2018-10-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterseq_app', '0005_auto_20181015_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeqBioInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_version', models.CharField(blank=True, max_length=200)),
                ('final_reads', models.IntegerField(blank=True, null=True)),
                ('final_yield', models.FloatField(blank=True, null=True)),
                ('mito_frac', models.FloatField(blank=True, null=True)),
                ('tss_enrichment', models.FloatField(blank=True, null=True)),
                ('frop', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeqInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_id', models.CharField(max_length=100, unique=True)),
                ('read_length', models.CharField(blank=True, max_length=50)),
                ('read_type', models.CharField(choices=[('SE', 'Single-end'), ('PE', 'Paired-end')], max_length=2, null=True)),
                ('portion_of_lane', models.FloatField(blank=True, null=True)),
                ('total_reads', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sequencinginfo',
            name='i5index',
        ),
        migrations.RemoveField(
            model_name='sequencinginfo',
            name='i7index',
        ),
        migrations.RemoveField(
            model_name='sequencinginfo',
            name='libraryinfo',
        ),
        migrations.RemoveField(
            model_name='sequencinginfo',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='sequencinginfo',
            name='team_member_initails',
        ),
        migrations.RenameModel(
            old_name='SequencingMachineInfo',
            new_name='SeqMachineInfo',
        ),
    ]
