# Generated by Django 2.0.6 on 2018-10-16 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setqc_app', '0021_auto_20181016_1057'),
        ('masterseq_app', '0006_auto_20181016_1057'),
        ('nextseq_app', '0012_auto_20180926_1126'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='SequencingInfo',
        ),
        migrations.AddField(
            model_name='seqinfo',
            name='i5index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequencing_i5_index', to='nextseq_app.Barcode'),
        ),
        migrations.AddField(
            model_name='seqinfo',
            name='i7index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequencing_i7_index', to='nextseq_app.Barcode'),
        ),
        migrations.AddField(
            model_name='seqinfo',
            name='libraryinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterseq_app.LibraryInfo'),
        ),
        migrations.AddField(
            model_name='seqinfo',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterseq_app.SeqMachineInfo'),
        ),
        migrations.AddField(
            model_name='seqinfo',
            name='team_member_initails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seqbioinfo',
            name='genome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterseq_app.GenomeInfo'),
        ),
        migrations.AddField(
            model_name='seqbioinfo',
            name='seqinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterseq_app.SeqInfo'),
        ),
    ]
