# Generated by Django 2.0.6 on 2018-10-16 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterseq_app', '0008_auto_20181016_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seqinfo',
            name='libraryinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterseq_app.LibraryInfo'),
        ),
    ]
