# Generated by Django 2.0.6 on 2018-10-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterseq_app', '0010_auto_20181016_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryinfo',
            name='experiment_type',
            field=models.CharField(choices=[('ATAC-seq', 'ATAC-seq'), ('ChIP-seq', 'ChIP-seq'), ('Hi-C Arima Kit', 'Hi-C Arima Kit'), ('Hi-C Epigen', 'Hi-C Epigen'), ('scATAC-seq', 'scATAC-seq'), ('scRNA-seq', 'scRNA-seq'), ('snRNA-seq', 'snRNA-seq'), ('4C', '4C'), ('CUT&RUN', 'CUT&RUN'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='species',
            field=models.CharField(choices=[('Human', 'Human'), ('Mouse', 'Mouse'), ('Other', 'Other')], max_length=10),
        ),
    ]
