# Generated by Django 2.0.6 on 2018-10-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterseq_app', '0012_auto_20181016_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='seqinfo',
            name='date_submitted_for_sequencing',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seqinfo',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='genomeinfo',
            name='species',
            field=models.CharField(choices=[('human', 'Human'), ('mouse', 'Mouse'), ('rat', 'rat'), ('other', 'other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='libraryinfo',
            name='experiment_type',
            field=models.CharField(choices=[('ATAC-seq', 'ATAC-seq'), ('ChIP-seq', 'ChIP-seq'), ('Hi-C', 'Hi-C'), ('scATAC-seq', 'scATAC-seq'), ('scRNA-seq', 'scRNA-seq'), ('snRNA-seq', 'snRNA-seq'), ('4C', '4C'), ('CUT&RUN', 'CUT&RUN'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='protocalinfo',
            name='experiment_type',
            field=models.CharField(choices=[('ATAC-seq', 'ATAC-seq'), ('ChIP-seq', 'ChIP-seq'), ('Hi-C', 'Hi-C'), ('scATAC-seq', 'scATAC-seq'), ('scRNA-seq', 'scRNA-seq'), ('snRNA-seq', 'snRNA-seq'), ('4C', '4C'), ('CUT&RUN', 'CUT&RUN'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='species',
            field=models.CharField(choices=[('human', 'Human'), ('mouse', 'Mouse'), ('rat', 'rat'), ('other', 'other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='seqinfo',
            name='read_type',
            field=models.CharField(choices=[('SE', 'Single-end'), ('PE', 'Paired-end'), ('Other (please explain in notes)', 'Other (please explain in notes)')], max_length=2, null=True),
        ),
    ]
