# Generated by Django 2.0.6 on 2018-10-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterseq_app', '0013_auto_20181023_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryinfo',
            name='experiment_type',
            field=models.CharField(choices=[('ATAC-seq', 'ATAC-seq'), ('ChIP-seq', 'ChIP-seq'), ('Hi-C', 'Hi-C'), ('scATAC-seq', 'scATAC-seq'), ('scRNA-seq', 'scRNA-seq'), ('snRNA-seq', 'snRNA-seq'), ('4C', '4C'), ('CUT&RUN', 'CUT&RUN'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
