# Generated by Django 2.0.6 on 2018-10-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterseq_app', '0014_auto_20181023_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seqinfo',
            name='read_type',
            field=models.CharField(choices=[('SE', 'Single-end'), ('PE', 'Paired-end'), ('Other (please explain in notes)', 'Other (please explain in notes)')], max_length=20, null=True),
        ),
    ]
