# Generated by Django 2.0.6 on 2018-11-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterseq_app', '0017_auto_20181023_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='seqinfo',
            name='default_label',
            field=models.CharField(blank=True, max_length=50, verbose_name='Default Label(for setQC report)'),
        ),
        migrations.AlterField(
            model_name='genomeinfo',
            name='species',
            field=models.CharField(choices=[('human', 'Human'), ('mouse', 'Mouse'), ('rat', 'rat'), ('other (please explain in notes)', 'other (please explain in notes)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='libraryinfo',
            name='experiment_type',
            field=models.CharField(choices=[('ATAC-seq', 'ATAC-seq'), ('ChIP-seq', 'ChIP-seq'), ('Hi-C', 'Hi-C'), ('scATAC-seq', 'scATAC-seq'), ('scRNA-seq', 'scRNA-seq'), ('snRNA-seq', 'snRNA-seq'), ('4C', '4C'), ('CUT&RUN', 'CUT&RUN'), ('other (please explain in notes)', 'other (please explain in notes)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='protocalinfo',
            name='experiment_type',
            field=models.CharField(choices=[('ATAC-seq', 'ATAC-seq'), ('ChIP-seq', 'ChIP-seq'), ('Hi-C', 'Hi-C'), ('scATAC-seq', 'scATAC-seq'), ('scRNA-seq', 'scRNA-seq'), ('snRNA-seq', 'snRNA-seq'), ('4C', '4C'), ('CUT&RUN', 'CUT&RUN'), ('other (please explain in notes)', 'other (please explain in notes)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='preparation',
            field=models.CharField(choices=[('flash frozen without cryopreservant', 'flash frozen without cryopreservant'), ('flash frozen with cryopreservant', 'flash frozen with cryopreservant'), ('slow frozen with cryopreservant', 'slow frozen with cryopreservant'), ('fresh', 'fresh'), ('other (please explain in notes)', 'other (please explain in notes)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='sample_type',
            field=models.CharField(choices=[('cultured cells', 'cultured cells'), ('isolated cells', 'isolated cells'), ('isolated nuclei', 'isolated nuclei'), ('PcA cell line', 'PcA cell line'), ('tissue', 'tissue'), ('other (please explain in notes)', 'other (please explain in notes)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='species',
            field=models.CharField(choices=[('human', 'Human'), ('mouse', 'Mouse'), ('rat', 'rat'), ('other (please explain in notes)', 'other (please explain in notes)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='seqinfo',
            name='read_type',
            field=models.CharField(choices=[('SE', 'Single-end'), ('PE', 'Paired-end'), ('other (please explain in notes)', 'other (please explain in notes)')], max_length=50, null=True),
        ),
    ]
