# Generated by Django 2.0.6 on 2018-11-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterseq_app', '0018_auto_20181105_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seqinfo',
            name='default_label',
            field=models.CharField(blank=True, max_length=200, verbose_name='Default Label(for setQC report)'),
        ),
    ]
