# Generated by Django 2.0.6 on 2018-11-06 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterseq_app', '0019_auto_20181105_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleinfo',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sampleinfo',
            name='team_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='sample_id',
            field=models.CharField(max_length=100, verbose_name='sample name'),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='sample_type',
            field=models.CharField(choices=[('cultured cells', 'cultured cells'), ('isolated cells', 'isolated cells'), ('isolated nuclei', 'isolated nuclei'), ('tissue', 'tissue'), ('other (please explain in notes)', 'other (please explain in notes)')], max_length=50),
        ),
    ]
