# Generated by Django 2.0.6 on 2018-08-27 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nextseq_app', '0011_librariesinrun_numberofreads'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrariesSetQC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setname', models.CharField(max_length=200, unique=True)),
                ('setID', models.CharField(max_length=20, unique=True)),
                ('date_requested', models.DateField(blank=True, help_text='If the datepicker is not working, \t\tplease enter in this form: yyyy-mm-dd, like 2018-04-03', null=True)),
                ('experiment_type', models.CharField(choices=[('ATAC-seq', 'ATAC-seq'), ('ChIP-seq', 'ChIP-seq'), ('HiC', 'HiC'), ('other', 'other')], max_length=2)),
                ('notes', models.CharField(max_length=200)),
                ('libraries_to_include', models.ManyToManyField(to='nextseq_app.LibrariesInRun')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
