# Generated by Django 2.0.4 on 2018-11-15 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterseq_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrariesSetQC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=200, unique=True)),
                ('set_id', models.CharField(max_length=20, unique=True)),
                ('date_requested', models.DateField(blank=True, help_text='If the datepicker is not working, \t\tplease enter in this form: yyyy-mm-dd, like 2018-04-03', null=True)),
                ('experiment_type', models.CharField(choices=[('ATAC-seq', 'ATAC-seq'), ('ChIP-seq', 'ChIP-seq'), ('HiC', 'HiC'), ('Other', 'Other')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(blank=True)),
                ('version', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, default='ClickToSubmit', max_length=200)),
                ('collaborator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaborator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryInSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(blank=True, max_length=10)),
                ('is_input', models.NullBooleanField(verbose_name='Is it input?')),
                ('label', models.CharField(blank=True, max_length=50)),
                ('genome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterseq_app.GenomeInfo')),
                ('librariesetqc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setqc_app.LibrariesSetQC')),
                ('seqinfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterseq_app.SeqInfo')),
            ],
        ),
        migrations.AddField(
            model_name='librariessetqc',
            name='libraries_to_include',
            field=models.ManyToManyField(through='setqc_app.LibraryInSet', to='masterseq_app.SeqInfo'),
        ),
        migrations.AddField(
            model_name='librariessetqc',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestor', to=settings.AUTH_USER_MODEL),
        ),
    ]
