# Generated by Django 2.0.6 on 2018-09-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setqc_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librariessetqc',
            old_name='setname',
            new_name='set_name',
        ),
    ]
