# Generated by Django 2.0.6 on 2018-09-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setqc_app', '0002_auto_20180902_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='librariessetqc',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
