# Generated by Django 2.0.6 on 2018-09-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setqc_app', '0003_librariessetqc_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librariessetqc',
            name='experiment_type',
            field=models.CharField(choices=[('ATAC-seq', 'ATAC-seq'), ('ChIP-seq', 'ChIP-seq'), ('HiC', 'HiC'), ('other', 'other')], max_length=10),
        ),
    ]
