# Generated by Django 2.0.6 on 2018-09-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setqc_app', '0004_auto_20180904_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='librariessetqc',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='librariessetqc',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
