# Generated by Django 2.0.6 on 2018-09-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setqc_app', '0005_auto_20180906_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librariessetqc',
            name='libraries_to_include',
            field=models.ManyToManyField(to='masterseq_app.SequencingInfo'),
        ),
    ]
