# Generated by Django 2.0.6 on 2018-09-18 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterseq_app', '0001_initial'),
        ('setqc_app', '0006_auto_20180910_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChipLibraryInSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(max_length=10)),
                ('is_input', models.BooleanField(default=False, verbose_name='Is it paired-end?')),
            ],
        ),
        migrations.AlterField(
            model_name='librariessetqc',
            name='experiment_type',
            field=models.CharField(choices=[('ATAC-seq', 'ATAC-seq'), ('ChIP-seq', 'ChIP-seq'), ('HiC', 'HiC'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='librariessetqc',
            name='libraries_to_include',
            field=models.ManyToManyField(related_name='reglibrary', to='masterseq_app.SequencingInfo'),
        ),
        migrations.AddField(
            model_name='chiplibraryinset',
            name='librarieseetqc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setqc_app.LibrariesSetQC'),
        ),
        migrations.AddField(
            model_name='chiplibraryinset',
            name='sequencinginfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterseq_app.SequencingInfo'),
        ),
        migrations.AddField(
            model_name='librariessetqc',
            name='libraries_to_include_forChIP',
            field=models.ManyToManyField(related_name='chiplibrary', through='setqc_app.ChipLibraryInSet', to='masterseq_app.SequencingInfo'),
        ),
    ]
