# Generated by Django 2.0.6 on 2018-09-18 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setqc_app', '0007_auto_20180918_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chiplibraryinset',
            old_name='librarieseetqc',
            new_name='librariesetqc',
        ),
    ]
