# Generated by Django 2.0.6 on 2018-09-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setqc_app', '0009_auto_20180924_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librariessetqc',
            old_name='report_status',
            new_name='status',
        ),
    ]
