# Generated by Django 2.0.6 on 2018-09-26 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setqc_app', '0010_auto_20180925_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librariessetqc',
            old_name='setID',
            new_name='set_id',
        ),
    ]
