# Generated by Django 2.0.6 on 2018-09-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setqc_app', '0011_auto_20180925_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiplibraryinset',
            name='is_input',
            field=models.BooleanField(default=False, verbose_name='Is it input?'),
        ),
    ]
