# Generated by Django 2.0.6 on 2018-10-02 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterseq_app', '0001_initial'),
        ('setqc_app', '0012_auto_20180926_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryInSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(blank=True, max_length=10)),
                ('is_input', models.BooleanField(verbose_name='Is it input?')),
            ],
        ),
        migrations.AddField(
            model_name='libraryinset',
            name='librariesetqc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setqc_app.LibrariesSetQC'),
        ),
        migrations.AddField(
            model_name='libraryinset',
            name='sequencinginfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterseq_app.SequencingInfo'),
        ),
    ]
