# Generated by Django 2.0.6 on 2018-10-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setqc_app', '0013_auto_20181001_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chiplibraryinset',
            name='librariesetqc',
        ),
        migrations.RemoveField(
            model_name='chiplibraryinset',
            name='sequencinginfo',
        ),
        migrations.RemoveField(
            model_name='librariessetqc',
            name='libraries_to_include_forChIP',
        ),
        migrations.AlterField(
            model_name='librariessetqc',
            name='libraries_to_include',
            field=models.ManyToManyField(through='setqc_app.LibraryInSet', to='masterseq_app.SequencingInfo'),
        ),

        migrations.DeleteModel(
            name='ChipLibraryInSet',
        ),
    ]
