# Generated by Django 2.0.6 on 2018-10-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setqc_app', '0014_auto_20181001_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryinset',
            name='is_input',
            field=models.NullBooleanField(verbose_name='Is it input?'),
        ),
    ]
