# Generated by Django 2.0.6 on 2018-10-08 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setqc_app', '0015_auto_20181002_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='librariessetqc',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaborator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='librariessetqc',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestor', to=settings.AUTH_USER_MODEL),
        ),
    ]
