# Generated by Django 2.0.6 on 2018-10-15 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterseq_app', '0002_genomeinfo_protocalinfo_sequencingmachineinfo'),
        ('setqc_app', '0016_auto_20181008_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='librariessetqc',
            name='genomeinfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterseq_app.GenomeInfo'),
        ),
    ]
