# Generated by Django 2.0.6 on 2018-10-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setqc_app', '0018_auto_20181015_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryinset',
            name='label',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
