# Generated by Django 2.0.6 on 2018-10-15 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterseq_app', '0005_auto_20181015_1455'),
        ('setqc_app', '0019_libraryinset_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librariessetqc',
            name='genome',
        ),
        migrations.AddField(
            model_name='libraryinset',
            name='genome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterseq_app.GenomeInfo'),
        ),
    ]
