# Generated by Django 2.0.6 on 2018-10-16 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterseq_app', '0006_auto_20181016_1057'),
        ('setqc_app', '0020_auto_20181015_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryinset',
            name='sequencinginfo',
        ),
        migrations.AddField(
            model_name='libraryinset',
            name='seqinfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterseq_app.SeqInfo'),
        ),
        migrations.AlterField(
            model_name='librariessetqc',
            name='libraries_to_include',
            field=models.ManyToManyField(through='setqc_app.LibraryInSet', to='masterseq_app.SeqInfo'),
        ),
    ]
