# Generated by Django 2.0.4 on 2018-04-24 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexid', models.CharField(max_length=200)),
                ('indexseq', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RunInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runid', models.CharField(max_length=200)),
                ('date', models.DateField(verbose_name='I did this run on...')),
                ('is_pe', models.BooleanField(default=True, verbose_name='Is it paired-end?')),
                ('reads_length', models.IntegerField(default=75)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SamplesInRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleid', models.CharField(max_length=200)),
                ('i5index', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i5_index', to='nextseq_app.Barcode')),
                ('i7index', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i7_index', to='nextseq_app.Barcode')),
                ('singlerun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextseq_app.RunInfo')),
            ],
        ),
    ]
