# Generated by Django 2.0.4 on 2018-05-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseq_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runinfo',
            name='read_type',
            field=models.CharField(choices=[('SE', 'Single-end'), ('PE', 'Paired-end')], max_length=2),
        ),
    ]
