# Generated by Django 2.0.4 on 2018-04-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseq_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runinfo',
            name='date',
            field=models.DateTimeField(verbose_name='I did this run on...'),
        ),
    ]
