# Generated by Django 2.0.4 on 2018-05-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseq_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplesinrun',
            name='sampleid',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
