# Generated by Django 2.0.6 on 2018-06-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextseq_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SamplesInRun',
            new_name='LibrariesInRun',
        ),
    ]
