# Generated by Django 2.0.4 on 2018-04-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseq_app', '0002_auto_20180423_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runinfo',
            name='date',
            field=models.DateField(verbose_name='I did this run on...'),
        ),
    ]
