# Generated by Django 2.0.6 on 2018-06-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseq_app', '0002_auto_20180626_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='runinfo',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
