# Generated by Django 2.0.6 on 2018-07-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseq_app', '0003_runinfo_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runinfo',
            name='read_length',
            field=models.CharField(help_text='if R1=R2=75, enter 75, if R1=50,R2=75, enter 50+75', max_length=50),
        ),
    ]
