# Generated by Django 2.0.4 on 2018-05-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseq_app', '0003_auto_20180423_2339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barcode',
            options={'ordering': ['indexid']},
        ),
        migrations.AlterModelOptions(
            name='runinfo',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='samplesinrun',
            options={'ordering': ['sampleid']},
        ),
        migrations.AlterField(
            model_name='runinfo',
            name='date',
            field=models.DateField(help_text='Please enter like this: 2018-04-30', verbose_name='I did this run on...'),
        ),
        migrations.AlterField(
            model_name='runinfo',
            name='runid',
            field=models.CharField(db_column='flowcell', max_length=200, unique=True),
        ),
    ]
