# Generated by Django 2.0.6 on 2018-06-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseq_app', '0003_runinfo_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
