# Generated by Django 2.0.6 on 2018-07-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseq_app', '0004_auto_20180702_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runinfo',
            name='read_length',
            field=models.CharField(help_text='e.g. if R1=R2=75, enter 75, if R1=50,R2=75, enter 50+75', max_length=50),
        ),
    ]
