# Generated by Django 2.0.4 on 2018-05-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseq_app', '0004_auto_20180523_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runinfo',
            name='runid',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
