# Generated by Django 2.0.6 on 2018-07-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseq_app', '0005_auto_20180709_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='runinfo',
            name='nextseqdir',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
