# Generated by Django 2.0.4 on 2018-05-24 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextseq_app', '0005_auto_20180523_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runinfo',
            old_name='runid',
            new_name='Flowcell',
        ),
    ]
