# Generated by Django 2.0.6 on 2018-07-17 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextseq_app', '0006_runinfo_nextseqdir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runinfo',
            name='nextseqdir',
        ),
    ]
