# Generated by Django 2.0.4 on 2018-05-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseq_app', '0006_auto_20180524_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='runinfo',
            name='read_type',
            field=models.CharField(choices=[('SE', 'Single-end'), ('PE', 'Paired-end')], default='PE', max_length=1),
        ),
    ]
