# Generated by Django 2.0.6 on 2018-07-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseq_app', '0007_remove_runinfo_nextseqdir'),
    ]

    operations = [
        migrations.AddField(
            model_name='runinfo',
            name='nextseqdir',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
