# Generated by Django 2.0.4 on 2018-05-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseq_app', '0008_auto_20180524_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runinfo',
            name='reads_length',
            field=models.IntegerField(),
        ),
    ]
