# Generated by Django 2.0.6 on 2018-07-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseq_app', '0008_runinfo_nextseqdir'),
    ]

    operations = [
        migrations.AddField(
            model_name='runinfo',
            name='jobid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='runinfo',
            name='jobstatus',
            field=models.CharField(blank=True, default='ToSubmit', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='runinfo',
            name='nextseqdir',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
