# Generated by Django 2.0.4 on 2018-05-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseq_app', '0009_auto_20180524_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runinfo',
            name='read_type',
            field=models.CharField(choices=[('SE', 'Single-end'), ('PE', 'Paired-end')], max_length=2),
        ),
    ]
