# Generated by Django 2.0.6 on 2018-07-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseq_app', '0009_auto_20180718_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runinfo',
            name='jobid',
        ),
        migrations.AlterField(
            model_name='runinfo',
            name='jobstatus',
            field=models.CharField(blank=True, default='ClickToSubmit', max_length=200, null=True),
        ),
    ]
