# Generated by Django 2.0.4 on 2018-05-24 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextseq_app', '0010_auto_20180524_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runinfo',
            old_name='reads_length',
            new_name='read_length',
        ),
        migrations.RemoveField(
            model_name='runinfo',
            name='is_pe',
        ),
    ]
