# Generated by Django 2.0.6 on 2018-07-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseq_app', '0010_auto_20180731_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='librariesinrun',
            name='numberofreads',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
