# Generated by Django 2.0.4 on 2018-05-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseq_app', '0011_auto_20180524_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runinfo',
            name='Flowcell',
            field=models.CharField(help_text='Please enter the FlowcellSerialNumber, like H5GLYBGX5', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='runinfo',
            name='date',
            field=models.DateField(blank=True, help_text='Please enter like this: 2018-04-30', null=True, verbose_name='I did this run on...'),
        ),
    ]
