# Generated by Django 2.0.6 on 2018-09-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseq_app', '0011_librariesinrun_numberofreads'),
    ]

    operations = [
        migrations.AddField(
            model_name='runinfo',
            name='percent_of_reads_demultiplexed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runinfo',
            name='total_libraries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runinfo',
            name='total_reads',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
