#!/bin/bash
#PBS -q home-epigen
#PBS -N django_10xPipeline_CellRanger
#PBS -l nodes=1:ppn=16
#PBS -l walltime=24:00:00
#PBS -l mem=96gb
#PBS -o /home/zhc268/logs/run_10xMkpipeline.out
#PBS -e /home/zhc268/logs/run_10xMkpipeline.err
#PBS -V
#PBS -m abe
#PBS -A epigen-group

# -v pass parameters: samples

export PATH=/projects/ps-epigen/software/cellranger-3.0.2/cellranger/:$PATH
WORKDIR="/oasis/tscc/scratch/$(whoami)/outputs_TA/"
FASTQDIR="/projects/ps-epigen/seqdata/"


# select libs 
samplenames=(`cat $samples`)
INPREFIX=${samplenames[${PBS_ARRAYID}*3]} #index start from 0
SAMPLE=${samplenames[${PBS_ARRAYID}*3+1]}
GENOME=${samplenames[${PBS_ARRAYID}*3+2]}
cd $WORKDIR

# prepare fastqs, comma seperated values
fastqs=$(echo $SAMPLE| awk -v FS=',' -v d="${FASTQDIR}" '{ for(i=1;i<=NF-1;i++) {printf "%s,", d$i};print d$NF;}')

#fastqs="${FASTQDIR}/${INPREFIX}"
#echo $fastqs
# [[ ! -d $fastqs ]] && { echo "$fastqs not found"; exit 0; }


# run pipeline
mkdir -p ~/data/outputs/scRNA/$INPREFIX
[[ -f ~/data/outputs/scRNA/${INPREFIX}/.inqueue ]] && rm  ~/data/outputs/scRNA/${INPREFIX}/.inqueue 
touch ~/data/outputs/scRNA/${INPREFIX}/.inprocess

############################################################
# update status from InQueue to InProcess
############################################################
cmd="source activate django; python \$(which updateSingleCellStatus.py) -seqid $INPREFIX -status InProcess;"
job1=$(ssh zhc268@epigenomics.sdsc.edu $cmd)

echo "cellranger count --id=$INPREFIX --fastqs=${fastqs} --sample ${SAMPLE} --transcriptome=${genome_path} --localcores=16  --mempercore=5"
cellranger count --id=$INPREFIX --fastqs=$fastqs --sample $SAMPLE --transcriptome=$genome_path --localcores=16  --mempercore=5
wait

# transfer results
rsync -azr ${WORKDIR}${INPREFIX} ~/data/outputs/scRNA/
rm  ~/data/outputs/scRNA/${INPREFIX}/.inprocess
## addtional check
#[[ -z $(find ${OUTDIR}/qc/rep1 -name "*_qc.txt") ]]  && { echo  "pipeline interrupted"; exit 0; }
wait

#TODO add a check to see if error file present if so then pass Error! to status

############################################################
# update status to finish or warning @ VM
############################################################
cmd="source activate django; python \$(which updateSingleCellStatus.py) -seqid $INPREFIX -status Yes;"
job1=$(ssh zhc268@epigenomics.sdsc.edu $cmd)
#update status in 

